### ISSUE TITLE
Any chance this could become an OSX screensaver? Please?

### ISSUE THREAD

**Issue by ErikPettersson** [notwaldorf/emoji-rain#1]

**Comment by notwaldorf** [comment]
Whoa, I've never tried to make a screensaver before. Sure, I'll look into it! :)

**Comment by ErikPettersson** [comment]
Excellent! (:

**Comment by redburn** [comment]
Visually it makes for a great screensaver, but the web demo is very taxing for the CPU... and so is the screensaver (attached). Use at your own risk :)
[Emoji Rain.saver.zip](https://github.com/notwaldorf/emoji-rain/files/290128/Emoji.Rain.saver.zip)

**Comment by notwaldorf** [comment]
Closing this since someone provided a sample, and there's no way I'll ever get around to doing this.
